version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-MySQL
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: backup
    volumes:
      - db:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile-PHP
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
